<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyBlogFVV.BLL\MyBlogFVV.BLL.csproj" />
    <ProjectReference Include="..\MyBlogFVV.DAL\MyBlogFVV.DAL.csproj" />
  </ItemGroup>

</Project>
